{% set name = "cssbeautifier" %}
{% set version = "1.14.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cssbeautifier-{{ version }}.tar.gz
  sha256: 40544c2b62bbcb64caa5e7f37a02df95654e5ce1bcacadac4ca1f3dc89c31513

build:
  entry_points:
    - css-beautify = cssbeautifier:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pytest
    - pip
  run:
    - python >=3.7,<4.0
    - jsbeautifier
    - six >=1.13.0
    - editorconfig >=0.12.2

test:
  imports:
    - cssbeautifier
  commands:
    - pip check
    - css-beautify --help
  requires:
    - pip

about:
  home: https://beautifier.io
  dev_url: https://github.com/beautify-web/js-beautify
  summary: CSS unobfuscator and beautifier.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
